{{- if not .Values.acinfinity.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acinfinity.fullname" . }}
  labels: {{- include "acinfinity.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACINFINITY_EMAIL: {{ required "acinfinity.email is required unless acinfinity.existingSecret is set" .Values.acinfinity.email | quote }}
  ACINFINITY_PASSWORD: {{ required "acinfinity.password is required unless acinfinity.existingSecret is set" .Values.acinfinity.password | quote }}
{{- end }}
